config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root 'home#index'

    get '/maintenance' => "home#maintenance"

    resources :posts, path: 'news-and-analysis' do
      put :publish
      put :featured
      put :pinned
      collection do
        get :preview
      end
    end

    resources :sub_sections

    resources :sections

    resources :web_pages, path: "content"

    get "content/:id" => "web_pages#show", as: "content"

    get 'feed' => 'posts#feed'

    # for cms pages
    get "about/who-we-are" => "content_management_pages#who_we_are"
    get "about/what-we-do" => "content_management_pages#what_we_do"
    get "resources/how-to-appeal" => "content_management_pages#appeal"
    get "privacy-policy" => "content_management_pages#privacy"
    get "about/faqs" => "faqs#index"

    resources :people

    get "/author/:id" => "posts#author", :as => "author"

    resources :faqs

    get "resources/further-readings" => "further_reads#index"
    resources :further_reads

    resources :home_fields

    resources :stories do
      put :publish
    end

    resources :platform_links
    resources :posts_themes
    resources :categories
    resources :social_media_platforms
    resources :languages
    resources :countries

    resources :quotes do
      put :featured
    end

    resources :questions
    resources :question_options

    resources :contacts_topics
    resources :contacts , except: :index
    get "/contacts" => "contacts#new"

    # redirect old form links to the new flow
    get "/submit-report", :to => redirect("/")
    get "/submit", :to => redirect("/")
    get "/submit-report/facebook", :to => redirect("/")
    get "/submit-report/twitter", :to => redirect("/")
    get "/submit-report/flickr", :to => redirect("/")
    get "/submit-report/youtube", :to => redirect("/")
    get "/submit-report/google", :to => redirect("/")
    get "/submit-report/instagram", :to => redirect("/")

    get "/admin/stories" => "stories#index"
    get "/admin/posts" => "posts#admin"

    # for backend ######
    get "/admin", :to => redirect("/users/sign_in")
    get "/admin/dashboard" => "home#dashboard"

    get "/admin/countries" => "countries#index"
    get "/admin/languages" => "languages#index"
    get "/admin/social_media_platforms" => "social_media_platforms#index"
    get "/admin/pages_questions" => "pages#pages_questions"
    post "/admin/update_page" =>"pages#update_page"
    post "/admin/update_message" =>"pages#update_message"
    get "/admin/questions" => "questions#index"
    get "/admin/related_questions" => "questions#related_questions"
    get "/admin/related_options" => "questions#related_options"
    get "/admin/question_users" => "question_users#index"

    get "/admin/people" => "people#index"
    get "/admin/content_management_pages" => "content_management_pages#index"
    get "/admin/home_fields" => "home_fields#admin"
    get "/admin/categories" => "categories#index"
    get "/admin/posts_themes" => "posts_themes#index"
    get "/admin/quotes" => "quotes#index"
    get "/admin/platform_links" => "platform_links#index"
    
    get "/admin/further_reads" => "further_reads#admin"
    get "/admin/faqs" => "faqs#admin"
    get "/admin/subscribes" => "subscribes#index"
    get "/admin/contacts_topics" => "contacts_topics#index"
    get "/admin/contacts" => "contacts#index"
    get "/admin/notifications" => "notifications#index"

    resources :notifications

    resources :icons, only: %i(index new create edit update destroy) do
      patch :toggle_availability, on: :member
    end


    post "/thanks" => "questions#submit"
    get '/ty' => 'questions#ty'

    # for errors
    match "/404" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    match "/500" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    match "/422" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    # match "*path" => "home#error", via: [ :get, :post, :patch, :delete ]

    resources :subscribes
    get "/subscribe_confirmation" => "subscribes#subscribe_confirmation"

    resources :pages_questions
    resources :question_user_submissions

    resources :content_management_pages
    resources :question_answers
    resources :question_users
    
    resources :pages

    resources :takedowns, only: %i(new create index destroy show) do
      collection do
        get "confirm/:token" => "takedowns#confirm", as: "confirm"
        get "submitted"
      end
    end
  end

  devise_for :users, :skip => [:registrations]                                        
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end

end

app/models/quote.rb
# Quote
#
# The every post can have quote 
#
class Quote < ApplicationRecord
  has_and_belongs_to_many :posts_themes, through: :quotes_posts_themes
  has_and_belongs_to_many :social_media_platforms, through: :quotes_social_media_platforms

  ransack_alias :searchable, translated_search_any(%i(author quote))

  default_scope { order("id DESC") }

  validates :author,:font_size,:quote, :presence => true

  translates :author, :quote, :twitter_text
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  before_action :set_quote_id, only: [:featured]
  before_action :authenticate_user!
  layout 'backend'

  def index
    @collection, @count, @query = backend_index(Quote)
  end

  def featured
    # featured the quote "Allow the admin to fix/unfix the quote from the backEnd"
    ReverseField(@quote,"featured")
    redirect_to admin_quotes_url , notice: 'The quote was successfully featured.'
  end

  def new
    @quote = Quote.new
    @platfroms = SocialMediaPlatform.all
    @themes = PostsTheme.all
  end

  def edit
    @platfroms = SocialMediaPlatform.all
    @themes = PostsTheme.all
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save

      # add the quote themes
      if params[:theme]
        params[:theme].each do |element|
          theme = PostsTheme.find(element)
          @quote.posts_themes << theme unless @quote.posts_themes.include?(theme)
        end
      else
        # to handle the empty array error
        @quote.posts_themes = []
      end

      # add the quote platforms
      if params[:platfrom]
        params[:platfrom].each do |element|
          platform = SocialMediaPlatform.find(element)
          @quote.social_media_platforms << platform unless @quote.social_media_platforms.include?(platform)
        end
      else
        # to handle the empty array error
        @quote.social_media_platforms = []
      end

      redirect_to admin_quotes_url, notice: 'The quote was successfully created.'
    else
      render :new , notice: @quote.errors
    end
  end

  def update
    if @quote.update(quote_params)

      # update the quote themes
      if params[:theme]
        # delete the old data
        @quote.posts_themes.delete_all
        # add the new themes
        params[:theme].each do |element|
          theme = PostsTheme.find(element)
          @quote.posts_themes << theme unless @quote.posts_themes.include?(theme)
        end
      end

      # update the quote platforms
      if params[:platfrom]
        # delete the old data
        @quote.social_media_platforms.delete_all
        # add the new themes
        params[:platfrom].each do |element|
          platform = SocialMediaPlatform.find(element)
          @quote.social_media_platforms << platform unless @quote.social_media_platforms.include?(platform)
        end
      end

      redirect_to admin_quotes_url, notice: 'The quote was successfully updated.'
    else
      render :edit , notice: @quote.errors
    end
  end

  def destroy
    @quote.destroy
    redirect_to admin_quotes_url, notice: 'The quote was successfully destroyed.'
  end

  private
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # using in featured / unfeatured methods
    def set_quote_id
      @quote = Quote.find(params[:quote_id])
    end

    def quote_params
      params.require(:quote).permit(:author, :font_size, :quote ,:twitter_text ,:featured)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fieldset clearfix">
    <p class="required"><b> Post platfroms *</b> </p>
    <% @platfroms.each_with_index do |platfrom , index| %>
      <div class="checkbox-wrapper">
      <%= label_tag "platfrom_#{index.to_s}", raw("#{check_box_tag("platfrom[]", platfrom.id, @quote.social_media_platforms.include?(platfrom),:id=>"platfrom_"+index.to_s)} #{platfrom.title}") %>
      </div>
    <% end %>
  </div>

  <div class="fieldset clearfix">
    <p class="required"><b> Post themes *</b> </p>
    <% @themes.each_with_index do |theme , index| %>
      <div class="checkbox-wrapper">
      <%= label_tag "theme_#{index.to_s}", raw("#{check_box_tag("theme[]", theme.id, @quote.posts_themes.include?(theme),:id=>"theme_"+index.to_s)} #{theme.title}") %>
      </div>
    <% end %>
  </div>
  
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author , required: true , :class=>"form-control"  %>
  </div>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_area :quote , required: true , :class=>"form-control text_area_height" %>
  </div>

  <div class="field">
    <%= f.label :twitter_text %><br>
    <%= f.text_area :twitter_text , required: true , :class=>"form-control", :maxlength => "99" %>
    <span class="tip"> Maximun 99 characters, "OC link and @censored" will be appended. </span>
  </div>
  <div class="field">
    <%= f.label :font_size %><br>
    <%= f.number_field :font_size , required: true , :class=>"form-control"  %>
  </div>
  <br>
  <div class="field">
    <%= f.check_box :featured %>
    <%= f.label :featured %>
  </div>

  <div class="actions">
    <%= f.submit :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<div class="col-md-12 col-sm-7 col-xs-12 no-padding">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="fa fa-pencil-square-o"></i>Editing quote
      </div>
    </div><!--panel-heading-->
    <div class="panel-body">
      <%= render 'form' %>
      <br />
      <%= link_to 'Show', @quote %> |
      <%= link_to 'All Quotes', admin_quotes_path %>
    </div><!--panel-body-->
  </div><!--content-box-large-->
</div><!--col-md-12-->

app/views/quotes/index.html.erb
<!--BackEnd page-->
<div class="content-box-large col-md-12 col-sm-7 col-xs-12">
  <div class="panel-heading">
    <div class="panel-title col-md-12">
      <i class="fa fa-quote-left"></i>
      Quotes
      <%= render 'home/admin_search' %>
      <br>
      <div class="sub-links col-md-12">
        <i class="fa fa-pencil-square-o"></i>
        <%= link_to 'New Quote', new_quote_path %>
        <i class="fa fa-file-excel-o"></i>
        <%= link_to "Export To Excel", quotes_path(format: "xls") %>
      </div>
    </div><!--panel-title-->
    <br>
  </div><!--panel-heading-->
  <div class="panel-body">

    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered sortable" id="example">
      <thead title="Click to short" class="cursor">
        <tr>
          <th>Author</th>
          <th>Font size</th>
          <th>Featured</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% if @collection.blank? %>
          <tr>
            <td colspan="100%" align="center" class="empty"><%= t('empty_table') %></td>
          </tr>
        <% else %>
          <% @collection.each do |quote| %>
            <tr class="show-image">
              <td><%= quote.author %></td>
              <td><%= quote.font_size %></td>
              <td class="icon-control">
                <% if quote.featured %>
                  <%= link_to quote_featured_path(quote.id), method: :put ,:title => "Click to Unfeature" do %>
                    <i class="fa fa-check check"></i>
                  <% end %>
                <% else %>
                  <%= link_to quote_featured_path(quote.id), method: :put ,:title => "Click to Feature" do %>
                    <i class="fa fa-times uncheck"></i>
                  <% end %>
                <% end %>
              </td>
              <td class="icon-control">
                <%= link_to quote, :title => "Show" do %><div class="backend-icon icon-show"></div><% end %>
              </td>
              <td class="icon-control">
                <%= link_to edit_quote_path(quote), :title => "Edit" do %><div class="backend-icon icon-edit"></div><% end %>
              </td>
              <td class="icon-control">
                <%= link_to quote, method: :delete, data: { confirm: 'Are you sure?' } ,:title => "Delete" do %><div class="backend-icon icon-delete"></div><% end %>
              </td>
            </tr>
          <% end %>
            <tfoot>
              <tr>
                <th colspan="100%"><%= paginate @collection %></th>
              </tr>
            </tfoot>
          <% end %>
      </tbody>
    </table>
  </div><!--panel-body-->
</div><!--content-box-large-->

app/views/quotes/index.xls.erb
<table width="100%" cellspacing="2">
  <tr>
    <th style="text-align:left; font-weight:bold;">Registered at</th>
    <th style="text-align:left; font-weight:bold;">Autheor</th>
    <th style="text-align:left; font-weight:bold;">Font Size</th>
    <th style="text-align:left; font-weight:bold;">Quote</th>
    <th style="text-align:left; font-weight:bold;">Featured</th>
  </tr>

  <% @collection.each do |excel| %>
    <tr>
      <td style="text-align:left;"><%= excel.created_at.to_date %></td>
      <td style="text-align:left;"><%= excel.author %></td>
      <td style="text-align:left;"><%= excel.font_size %></td>
      <td style="text-align:left;"><%= excel.quote %></td>
      <td style="text-align:left;"><%= excel.featured %></td>
    </tr>
  <% end %>

</table>

app/views/quotes/new.html.erb
<div class="col-md-12 col-sm-7 col-xs-12 no-padding">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="fa fa-pencil-square-o"></i>New quote
      </div>
    </div><!--panel-heading-->
    <div class="panel-body">
      <%= render 'form' %>
      <br>
      <%= link_to 'All Quotes', admin_quotes_path %>
    </div><!--panel-body-->
  </div><!--content-box-large-->
</div><!--col-md-12-->

app/views/quotes/show.html.erb
<div class="col-md-12 col-sm-7 col-xs-12 no-padding">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="fa fa-quote-left"></i>Quote Details
      </div>
    </div><!--panel-heading-->
    <div class="panel-body">
      <div class="col-md-12 details">

				<p>
				  <strong>Author:</strong>
				  <%= @quote.author %>
				</p>

        <p>
          <strong>Font size:</strong>
          <%= @quote.font_size %>
        </p>

				<p>
				  <strong>Quote:</strong>
				  <%= @quote.quote %>
				</p>

        <p>
          <strong>Twitter text:</strong>
          <%= @quote.twitter_text %>
        </p>
            
        <p>
          <strong>Featured:</strong>
          <% if @quote.featured %>
            <%= link_to "Unfeatured", quote_unfeatured_path(@quote.id) %>
          <% else %>
            <%= link_to "Featured", quote_featured_path(@quote.id) %>
          <% end %>
        </p>

        <p>
          <%= link_to 'Edit', edit_quote_path(@quote) %> |
          <%= link_to 'All Quotes', admin_quotes_path %>
        </p>
    
      </div><!--details-->
    </div><!--panel-body-->
  </div><!--content-box-large-->
</div><!--col-md-12-->