config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root 'home#index'

    get '/maintenance' => "home#maintenance"

    resources :posts, path: 'news-and-analysis' do
      put :publish
      put :featured
      put :pinned
      collection do
        get :preview
      end
    end

    resources :sub_sections

    resources :sections

    resources :web_pages, path: "content"

    get "content/:id" => "web_pages#show", as: "content"

    get 'feed' => 'posts#feed'

    # for cms pages
    get "about/who-we-are" => "content_management_pages#who_we_are"
    get "about/what-we-do" => "content_management_pages#what_we_do"
    get "resources/how-to-appeal" => "content_management_pages#appeal"
    get "privacy-policy" => "content_management_pages#privacy"
    get "about/faqs" => "faqs#index"

    resources :people

    get "/author/:id" => "posts#author", :as => "author"

    resources :faqs

    get "resources/further-readings" => "further_reads#index"
    resources :further_reads

    resources :home_fields

    resources :stories do
      put :publish
    end

    resources :platform_links
    resources :posts_themes
    resources :categories
    resources :social_media_platforms
    resources :languages
    resources :countries

    resources :quotes do
      put :featured
    end

    resources :questions
    resources :question_options

    resources :contacts_topics
    resources :contacts , except: :index
    get "/contacts" => "contacts#new"

    # redirect old form links to the new flow
    get "/submit-report", :to => redirect("/")
    get "/submit", :to => redirect("/")
    get "/submit-report/facebook", :to => redirect("/")
    get "/submit-report/twitter", :to => redirect("/")
    get "/submit-report/flickr", :to => redirect("/")
    get "/submit-report/youtube", :to => redirect("/")
    get "/submit-report/google", :to => redirect("/")
    get "/submit-report/instagram", :to => redirect("/")

    get "/admin/stories" => "stories#index"
    get "/admin/posts" => "posts#admin"

    # for backend ######
    get "/admin", :to => redirect("/users/sign_in")
    get "/admin/dashboard" => "home#dashboard"

    get "/admin/countries" => "countries#index"
    get "/admin/languages" => "languages#index"
    get "/admin/social_media_platforms" => "social_media_platforms#index"
    get "/admin/pages_questions" => "pages#pages_questions"
    post "/admin/update_page" =>"pages#update_page"
    post "/admin/update_message" =>"pages#update_message"
    get "/admin/questions" => "questions#index"
    get "/admin/related_questions" => "questions#related_questions"
    get "/admin/related_options" => "questions#related_options"
    get "/admin/question_users" => "question_users#index"

    get "/admin/people" => "people#index"
    get "/admin/content_management_pages" => "content_management_pages#index"
    get "/admin/home_fields" => "home_fields#admin"
    get "/admin/categories" => "categories#index"
    get "/admin/posts_themes" => "posts_themes#index"
    get "/admin/quotes" => "quotes#index"
    get "/admin/platform_links" => "platform_links#index"
    
    get "/admin/further_reads" => "further_reads#admin"
    get "/admin/faqs" => "faqs#admin"
    get "/admin/subscribes" => "subscribes#index"
    get "/admin/contacts_topics" => "contacts_topics#index"
    get "/admin/contacts" => "contacts#index"
    get "/admin/notifications" => "notifications#index"

    resources :notifications

    resources :icons, only: %i(index new create edit update destroy) do
      patch :toggle_availability, on: :member
    end


    post "/thanks" => "questions#submit"
    get '/ty' => 'questions#ty'

    # for errors
    match "/404" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    match "/500" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    match "/422" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    # match "*path" => "home#error", via: [ :get, :post, :patch, :delete ]

    resources :subscribes
    get "/subscribe_confirmation" => "subscribes#subscribe_confirmation"

    resources :pages_questions
    resources :question_user_submissions

    resources :content_management_pages
    resources :question_answers
    resources :question_users
    
    resources :pages

    resources :takedowns, only: %i(new create index destroy show) do
      collection do
        get "confirm/:token" => "takedowns#confirm", as: "confirm"
        get "submitted"
      end
    end
  end

  devise_for :users, :skip => [:registrations]                                        
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end

end

app/models/notification.rb
# Notification
#
# The admin can add stuff emails to the notifications system
#
class Notification < ApplicationRecord
  ransack_alias :searchable, %w(email name).join('_or_')

  # Validation
  validates :name, :presence => true
  validates :email, presence: true, uniqueness: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP,
                              message: "Please submit a valid email address" }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  layout 'backend'

  def index
    @collection, @count, @query = backend_index(Notification, translation: false)
  end

  def new
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    if @notification.save
      redirect_to admin_notifications_url, notice: 'The notification was successfully created.'
    else
      render :nothing => true  , notice: @notification.errors
    end
  end

  def update
    if @notification.update(notification_params)
      redirect_to admin_notifications_url, notice: 'The notification was successfully updated.'
    else
      render :edit, notice: @notification.errors
    end
  end

  def destroy
    @notification.destroy
    redirect_to admin_notifications_url, notice: 'The notification was successfully destroyed.'
  end

  private
    def set_notification
      @notification = Notification.find(params[:id])
    end

    def notification_params
      params.require(:notification).permit(:name, :email, :submit_report, :contact_us, :subscriber)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name ,required: true , :class=>"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email ,required: true , :class=>"form-control" , :pattern => "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" %>
  </div>
  <div class="field">
    <%= f.check_box :submit_report %>
    <%= f.label :submit_report %>
  </div>
  <div class="field">
    <%= f.check_box :contact_us %>
    <%= f.label :contact_us %>
  </div>
  <div class="field">
    <%= f.check_box :subscriber %>
    <%= f.label :subscriber %>
  </div>
  <div class="actions">
    <%= f.submit :class=> "btn btn-primary" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<div class="col-md-12 col-sm-7 col-xs-12 no-padding">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="fa fa-pencil-square-o"></i>Editing notification
      </div>
    </div><!--panel-heading-->
    <div class="panel-body">
      <%= render 'form' %>
      <br />
      <%= link_to 'Show', @notification %> |
      <%= link_to 'All Notifications', admin_notifications_path %>
    </div><!--panel-body-->
  </div><!--content-box-large-->
</div><!--col-md-12-->

app/views/notifications/index.html.erb
<!--BackEnd page-->
<div class="content-box-large col-md-12 col-sm-7 col-xs-12">
  <div class="panel-heading">
    <div class="panel-title col-md-12">
      <i class="fa fa-bell"></i>
      Notifications
      <%= render 'home/admin_search' %>
      <br>
      <div class="sub-links col-md-12">
        <i class="fa fa-pencil-square-o"></i>
        <%= link_to 'New Notification', new_notification_path %>
        <i class="fa fa-file-excel-o"></i>
        <%= link_to "Export To Excel", notifications_path(format: "xls") %>
      </div>
    </div><!--panel-title-->
    <br>
  </div><!--panel-heading-->
  <div class="panel-body">

    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered sortable" id="example">
      <thead title="Click to short" class="cursor">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% if @collection.blank? %>
          <tr>
            <td colspan="100%" align="center" class="empty"><%= t('empty_table') %></td>
          </tr>
        <% else %>
          <% @collection.each do |notification| %>
            <tr class="show-image">
              <td><%= notification.name %></td>
              <td><%= notification.email %></td>
              <td class="icon-control">
                <%= link_to notification, :title => "Show" do %><div class="backend-icon icon-show"></div><% end %>
              </td>
              <td class="icon-control">
                <%= link_to edit_notification_path(notification), :title => "Edit" do %><div class="backend-icon icon-edit"></div><% end %>
              </td>
              <td class="icon-control">
                <%= link_to notification, method: :delete, data: { confirm: 'Are you sure?' } ,:title => "Delete" do %><div class="backend-icon icon-delete"></div><% end %>
              </td>
            </tr>
          <% end %>
            <tfoot>
              <tr>
                <th colspan="100%"><%= paginate @collection %></th>
              </tr>
            </tfoot>
          <% end %>
      </tbody>
    </table>
  </div><!--panel-body-->
</div><!--content-box-large-->

app/views/notifications/index.xls.erb
<table width="100%" cellspacing="2">
  <tr>
    <th style="text-align:left; font-weight:bold;">Registered at</th>
    <th style="text-align:left; font-weight:bold;">Name</th>
    <th style="text-align:left; font-weight:bold;">Email</th>
  </tr>

  <% @collection.each do |excel| %>
    <tr>
      <td style="text-align:left;"><%= excel.created_at.to_date %></td>
      <td style="text-align:left;"><%= excel.name %></td>
      <td style="text-align:left;"><%= excel.email %></td>
    </tr>
  <% end %>

</table>

app/views/notifications/new.html.erb
<div class="col-md-12 col-sm-7 col-xs-12 no-padding">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="fa fa-pencil-square-o"></i>New notification
      </div>
    </div><!--panel-heading-->
    <div class="panel-body">
      <%= render 'form' %>
      <br>
      <%= link_to 'All Notifications', admin_notifications_path %>
    </div><!--panel-body-->
  </div><!--content-box-large-->
</div><!--col-md-12-->

app/views/notifications/show.html.erb
<div class="col-md-12 col-sm-7 col-xs-12 no-padding">
  <div class="content-box-large">
    <div class="panel-heading">
      <div class="panel-title">
        <i class="fa fa-bell"></i>Notification Details
      </div>
    </div><!--panel-heading-->
    <div class="panel-body">
      <div class="col-md-12 details">

        <p>
          <strong>Name:</strong>
          <%= @notification.name %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @notification.email %>
        </p>

        <p>
          <strong>Submit report:</strong>
          <%= @notification.submit_report %>
        </p>

        <p>
          <strong>Contact us:</strong>
          <%= @notification.contact_us %>
        </p>

        <p>
          <strong>Subscriber:</strong>
          <%= @notification.subscriber %>
        </p>

        <p>
          <%= link_to 'Edit', edit_notification_path(@notification) %> |
          <%= link_to 'All Notifications', admin_notifications_path %>
        </p>
      </div><!--details-->
    </div><!--panel-body-->
  </div><!--content-box-large-->
</div><!--col-md-12-->