config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do

    root 'home#index'

    get '/maintenance' => "home#maintenance"

    resources :posts, path: 'news-and-analysis' do
      put :publish
      put :featured
      put :pinned
      collection do
        get :preview
      end
    end

    resources :sub_sections

    resources :sections

    resources :web_pages, path: "content"

    get "content/:id" => "web_pages#show", as: "content"

    get 'feed' => 'posts#feed'

    # for cms pages
    get "about/who-we-are" => "content_management_pages#who_we_are"
    get "about/what-we-do" => "content_management_pages#what_we_do"
    get "resources/how-to-appeal" => "content_management_pages#appeal"
    get "privacy-policy" => "content_management_pages#privacy"
    get "about/faqs" => "faqs#index"

    resources :people

    get "/author/:id" => "posts#author", :as => "author"

    resources :faqs

    get "resources/further-readings" => "further_reads#index"
    resources :further_reads

    resources :home_fields

    resources :stories do
      put :publish
    end

    resources :platform_links
    resources :posts_themes
    resources :categories
    resources :social_media_platforms
    resources :languages
    resources :countries

    resources :quotes do
      put :featured
    end

    resources :questions
    resources :question_options

    resources :contacts_topics
    resources :contacts , except: :index
    get "/contacts" => "contacts#new"

    # redirect old form links to the new flow
    get "/submit-report", :to => redirect("/")
    get "/submit", :to => redirect("/")
    get "/submit-report/facebook", :to => redirect("/")
    get "/submit-report/twitter", :to => redirect("/")
    get "/submit-report/flickr", :to => redirect("/")
    get "/submit-report/youtube", :to => redirect("/")
    get "/submit-report/google", :to => redirect("/")
    get "/submit-report/instagram", :to => redirect("/")

    get "/admin/stories" => "stories#index"
    get "/admin/posts" => "posts#admin"

    # for backend ######
    get "/admin", :to => redirect("/users/sign_in")
    get "/admin/dashboard" => "home#dashboard"

    get "/admin/countries" => "countries#index"
    get "/admin/languages" => "languages#index"
    get "/admin/social_media_platforms" => "social_media_platforms#index"
    get "/admin/pages_questions" => "pages#pages_questions"
    post "/admin/update_page" =>"pages#update_page"
    post "/admin/update_message" =>"pages#update_message"
    get "/admin/questions" => "questions#index"
    get "/admin/related_questions" => "questions#related_questions"
    get "/admin/related_options" => "questions#related_options"
    get "/admin/question_users" => "question_users#index"

    get "/admin/people" => "people#index"
    get "/admin/content_management_pages" => "content_management_pages#index"
    get "/admin/home_fields" => "home_fields#admin"
    get "/admin/categories" => "categories#index"
    get "/admin/posts_themes" => "posts_themes#index"
    get "/admin/quotes" => "quotes#index"
    get "/admin/platform_links" => "platform_links#index"
    
    get "/admin/further_reads" => "further_reads#admin"
    get "/admin/faqs" => "faqs#admin"
    get "/admin/subscribes" => "subscribes#index"
    get "/admin/contacts_topics" => "contacts_topics#index"
    get "/admin/contacts" => "contacts#index"
    get "/admin/notifications" => "notifications#index"

    resources :notifications

    resources :icons, only: %i(index new create edit update destroy) do
      patch :toggle_availability, on: :member
    end


    post "/thanks" => "questions#submit"
    get '/ty' => 'questions#ty'

    # for errors
    match "/404" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    match "/500" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    match "/422" =>  "home#error", via: [ :get, :post, :patch, :delete ]
    # match "*path" => "home#error", via: [ :get, :post, :patch, :delete ]

    resources :subscribes
    get "/subscribe_confirmation" => "subscribes#subscribe_confirmation"

    resources :pages_questions
    resources :question_user_submissions

    resources :content_management_pages
    resources :question_answers
    resources :question_users
    
    resources :pages

    resources :takedowns, only: %i(new create index destroy show) do
      collection do
        get "confirm/:token" => "takedowns#confirm", as: "confirm"
        get "submitted"
      end
    end
  end

  devise_for :users, :skip => [:registrations]                                        
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
    put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'backend', only: [:dashboard]
  before_action :authenticate_user! , only: [:dashboard]

  def index
    @home_fields = HomeField.last
    @all_posts = Post.where(:published=>true).order("id DESC")

    if I18n.locale != :en
      @translated_posts = Post.with_translations(I18n.locale).where(:published=>true).order("id DESC").limit(7)
      @other_posts = Post.where(:published=>true).order("id DESC").where(:pinned=>true).limit(7)
      #@all_posts = @translated_posts + @other_posts
      posts = @translated_posts + @other_posts
      @posts = posts.uniq
    else
      # binding.pry
      @featured_post = Post.where(:published=>true).where(:featured=>true).order("updated_at DESC").first
      # binding.pry
      if @featured_post
        # show only the pinned posts and disable reviewing the featured post
        @posts = @all_posts.where.not(:id => @featured_post.id).where(:pinned=>true).limit(7)
      else
        # show only the pinned posts
        @posts = @all_posts.where(:pinned=>true).limit(9)
      end
    end
    @stories = Story.where(:published=>true)
  end

  # BackEnd dashboard
  def dashboard
    posts = Post.all.order("id DESC")
    @latest_posts = posts.where(published: true).limit(5)
    @draft_posts = posts.where(published: false).limit(5)
    @pinned_posts = posts.where(published: true).where(pinned: true).limit(5)
    @featured_post = posts.where(published: true).where(featured: true).first
    @pages = ContentManagementPage.all
    @people = Person.limit(6)
    @quotes = Quote.limit(5)
    stories = Story.all
    @published_stories = stories.where(published: true).limit(5)
    @unpublished_stories = stories.where(published: false).limit(5)
  end

  # Error page
  def error
    respond_to do |format|
      format.html { }
      format.all { redirect_to root_path }
    end
  end

  def maintenance
  end

end

app/views/home/_admin_search.erb
<% if params[:q]%>
  - search results for "<%= params[:q][:searchable_cont] %>" (<%=@count%> found)
  <div class="pull-right search-wrapper col-md-6">
    <%=link_to "Show All", controller_name,:class=>'pull-right btn btn-primary btn-xs search-btn'%>
  </div>
<% else %>
  <div class="pull-right search-wrapper col-md-6">
    <%= search_form_for @query, url: @url do |f| %>
      <%= f.search_field :searchable_cont %>
      <%= f.submit %>
    <% end %>
  </div>
<% end %>

app/views/home/_carousel.html.erb
<section class="carousel dark-blue-bg">
  <div class="owl-carousel">
    <% if @stories %>
      <% @stories.each do |story| %>
        <div class="story-wrapper">
          <div class="story clearfix">
            <div class="image">
              <% if story.external_link? %>
                <%=link_to story.external_link , :target => "_blank" do %>
                  <%= image_tag story.photo(:thumb) %>
                <% end %>
              <% else %>
                <%=link_to story_path(story),:title=>story.title do %>
                  <%= image_tag story.photo(:thumb) %>
                <% end %>
              <% end %>
            </div>
            <div class="story-content">
              <h1>
                <% if story.external_link? %>
                  <%=link_to story.external_link , :target => "_blank", class: 'h3' do %>
                    <%=story.title %>
                  <% end %>
                <% else %>
                  <%=link_to story_path(story),:title=>story.title, class: 'h3' do %>
                    <%=story.title %>
                  <% end %>
                <% end %>
              </h1>
              <p class="post-brief"><%= story.brief.truncate(175) %></p>
              <% if story.external_link? %>
                <%= link_to t(:read_story), story.external_link, target: "_blank", :class => "read-link more-link" %>
              <% else %>
                <%= link_to t(:read_story), story_path(story), :class => "read-link more-link" %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/home/_header.html.erb
<section class="dotted-bg intro">
  <div class="container">
    <div class="row">
      <div class="col-md-8">

        <% if locale == :en %>
          <h3 class="cd-headline letters type">
            <span> Has your</span>
            <span class="cd-words-wrapper">
              <b class="is-visible" style="opacity: 1;"><i class="in">a</i><i class="out">c</i><i class="out">c</i><i class="out">o</i><i class="out">u</i><i class="out">n</i><i class="out">t</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">p</i><i class="out">o</i><i class="out">s</i><i class="out">t</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">p</i><i class="out">h</i><i class="out">o</i><i class="out">t</i><i class="out">o</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">l</i><i class="out">i</i><i class="out">n</i><i class="out">k</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">c</i><i class="out">a</i><i class="out">m</i><i class="out">p</i><i class="out">a</i><i class="out">i</i><i class="out">g</i><i class="out">n</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
            </span>
          </h3><h3 class="cd-headline letters type">
            <span>been</span>
            <span class="cd-words-wrapper">
              <b class="is-visible" style="opacity: 1;"><i class="in">s</i><i class="out">u</i><i class="out">s</i><i class="out">p</i><i class="out">e</i><i class="out">n</i><i class="out">d</i><i class="out">e</i><i class="out">d</i><i class="out">?</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">c</i><i class="out">e</i><i class="out">n</i><i class="out">s</i><i class="out">o</i><i class="out">r</i><i class="out">e</i><i class="out">d</i><i class="out">?</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">t</i><i class="out">a</i><i class="out">k</i><i class="out">e</i><i class="out">n</i><i class="out"> </i><i class="out">d</i><i class="out">o</i><i class="out">w</i><i class="out">n</i><i class="out">?</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">r</i><i class="out">e</i><i class="out">m</i><i class="out">o</i><i class="out">v</i><i class="out">e</i><i class="out">d</i><i class="out">?</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">b</i><i class="out">a</i><i class="out">n</i><i class="out">n</i><i class="out">e</i><i class="out">d</i><i class="out">?</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
            </span>
          </h3>
        <% elsif locale == :ar %>
          <h3> هل تم <span class="dark-blue-bg"> حجب </span> </h3>
          <h3><span class="dark-blue-bg"> تدوينتك؟ </span></h3>
        <% else %>
          <h3 class="cd-headline letters type">
            <span> ¿Tu </span>
            <span class="cd-words-wrapper">
              <b class="is-visible" style="opacity: 1;"><i class="in">c</i><i class="out">u</i><i class="out">e</i><i class="out">n</i><i class="out">t</i><i class="out">a</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">p</i><i class="out">o</i><i class="out">s</i><i class="out">t</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">f</i><i class="out">o</i><i class="out">t</i><i class="out">o</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">e</i><i class="out">n</i><i class="out">l</i><i class="out">a</i><i class="out">c</i><i class="out">e</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">c</i><i class="out">a</i><i class="out">m</i><i class="out">p</i><i class="out">a</i><i class="out">ñ</i><i class="out">a</i><i class="out">/</i><i class="out">/</i><i class="out">/</i><i class="out">/</i></b>
            </span>
          </h3><h3 class="cd-headline letters type">
            <span> ha sido </span>
            <span class="cd-words-wrapper">
              <b class="is-visible" style="opacity: 1;"><i class="in">s</i><i class="out">u</i><i class="out">s</i><i class="out">p</i><i class="out">e</i><i class="out">n</i><i class="out">d</i><i class="out">i</i><i class="out">d</i><i class="out">a</i><i class="out">?</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">c</i><i class="out">e</i><i class="out">n</i><i class="out">s</i><i class="out">u</i><i class="out">r</i><i class="out">a</i><i class="out">d</i><i class="out">o</i><i class="out">?</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">r</i><i class="out">e</i><i class="out">t</i><i class="out">i</i><i class="out">r</i><i class="out">a</i><i class="out">d</i><i class="out">a</i><i class="out">?</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">r</i><i class="out">e</i><i class="out">m</i><i class="out">o</i><i class="out">v</i><i class="out">i</i><i class="out">d</i><i class="out">o</i><i class="out">?</i><i class="out">/</i><i class="out">/</i></b>
              <b class="is-hidden" style="opacity: 1;"><i class="out">p</i><i class="out">r</i><i class="out">o</i><i class="out">h</i><i class="out">i</i><i class="out">b</i><i class="out">i</i><i class="out">d</i><i class="out">a</i><i class="out">?</i><i class="out">/</i></b>
            </span>
          </h3>
        <% end %>

        <div class="row">
          <p class="col-md-9">
            <%=@home_fields.slogan%>
          </p>
        </div>
      </div>
      <div class="col-md-4 action">
        <%= image_tag("jail-cell", class: 'hidden-sm hidden-xs center-block') %>
      </div>
    </div>
  </div>
</section>

app/views/home/_news.html.erb
<section class="latest-news gray-bg news-area">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1> <%= t(:latest_news_analysis) %> </h1>
      </div>
    </div>
    <div class="row">
      <% if @featured_post %>
        <% if @featured_post.photo_file_name %>
          <div class="col-md-8">
            <div class="news-box featured-post clearfix">
              <div class="col-md-6 col-no-padding">
                <div class="image-wrapper">
                  <% if @featured_post.category && @featured_post.category.title.downcase=="news" %>
                    <%=link_to @featured_post.link , :target => "_blank" do %>
                      <%=image_tag @featured_post.photo(:thumb) %>
                    <% end %>
                  <% else %>
                    <%=link_to @featured_post, :title=>@featured_post.title do %>
                      <%=image_tag @featured_post.photo(:thumb) %>
                    <% end %>
                  <% end %>
                  <% if @featured_post.image_link.present? && @featured_post.image_author_name.present? && @featured_post.cc_license.present? %>
                    <div class="image-tip">
                      <a href="<%=@featured_post.image_link%>" target="_blank"><%= t(:image) %></a>
                      <%= t(:by) %> <a href="<%=@featured_post.image_author_link%>" target="_blank"><%=@featured_post.image_author_name%></a>
                      <a href="<%=@featured_post.cc_license%>" target="_blank"><%= t(:cc_license) %></a>
                    </div><!--image-tip-->
                  <% end %>
                </div>
              </div>
              <div class="col-md-6 col-no-padding">
                <div class="news-box featured">
                  <%= render partial: 'posts/card', locals: { post: @featured_post } %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div class="col-md-4">
            <div class="news-box">
              <%= render partial: 'posts/card', locals: { post: @featured_post } %>
            </div>
          </div>
        <% end %>
      <% end %>
      <% @posts.each do |post| %>
        <div class="col-md-4">
          <div class="news-box">
            <%= render partial: 'posts/card', locals: { post: post } %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-12 centered">
        <%= link_to posts_path do %>
          <div class="btn btn-default more-btn"> <%= t(:more_news_analysis) %> </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/_permissions_notifications.erb
<div class="content-box-large col-md-4 permission-box">
  <div class="panel-heading">
    <div class="panel-title col-md-12">
      <i class="fa fa-exclamation-triangle"></i>
        <%= t('need_login') %>
        <br /><br />
        <%= link_to "Log in", new_user_session_path, :class => "btn btn-primary" %>
    </div><!--panel-title-->
  </div><!--panel-heading-->
</div><!--content-box-large-->

app/views/home/dashboard.erb
<!--BackEnd page-->
<% if user_signed_in? %>
  <div class="col-md-12 col-sm-7 col-xs-12 no-padding">
    <div class="content-box-header">
      <div class="panel-title">Stories</div>
    </div><!--content-box-header-->
    <div class="admin-content-box content-box-large box-with-header">
      <div class="row">

        <div class="col-md-6">
          <h3> Recently Published </h3>
          <ul>
          <% @published_stories.each do |ps| %>
            <li> <%= link_to ps.title, edit_story_path(ps) %> </li>
          <% end %>
          </ul>
        </div>

        <div class="col-md-6">
          <h3> Unpublished </h3>
          <ul>
          <% @unpublished_stories.each do |us| %>
            <li> <%= link_to us.title, edit_story_path(us) %> </li>
          <% end %>
          </ul>
        </div>

      </div>

      <div class="admin-links">
        <i class="fa fa-pencil-square-o"></i>
        <%= link_to 'Manage Stories', admin_stories_path %>
      </div>
    </div><!--content-box-large-->
  </div><!--col-md-12-->

  <div class="col-md-12 col-sm-7 col-xs-12 no-padding">
    <div class="content-box-header">
      <div class="panel-title">News/Analysis</div>
    </div><!--content-box-header-->
    <div class="admin-content-box content-box-large box-with-header">
      <div class="row">

        <div class="col-md-6">
          <h3> Latest </h3>
          <ul>
          <% @latest_posts.each do |lp| %>
            <li> <%= link_to lp.title, edit_post_path(lp) %> </li>
          <% end %>
          </ul>
        </div>

        <div class="col-md-6">
          <h3> Drafts </h3>
          <ul>
          <% @draft_posts.each do |dp| %>
            <li> <%= link_to dp.title, edit_post_path(dp) %> </li>
          <% end %>
          </ul>
        </div>

      </div>

      <div class="row">

        <div class="col-md-6">
          <h3> Pinned </h3>
          <p class="tip"> Posts selected to appear on home page. </p>
          <ul>
          <% @pinned_posts.each do |pp| %>
            <li> <%= link_to pp.title, edit_post_path(pp) %> </li>
          <% end %>
          </ul>
        </div>

        <div class="col-md-6">
          <h3> Featured </h3>
          <p class="tip"> Only latest featured post will be displayed on home page. </p>
          <ul>
            <% if @featured_post.nil? %>
              <li> There are no posts yet. </li>
            <% else %>
              <li> <%= link_to @featured_post.title, edit_post_path(@featured_post) %> </li>
            <% end %>
          </ul>
        </div>

      </div><!--row-->

      <div class="admin-links">
        <i class="fa fa-pencil-square-o"></i>
        <%= link_to 'Manage Posts', admin_posts_path %> .
        <%= link_to 'Manage Categories', admin_categories_path %> .
        <%= link_to 'Manage Themes', admin_posts_themes_path %>
      </div>
    </div><!--content-box-large-->
  </div><!--col-md-12-->


  <div class="col-md-12 col-sm-7 col-xs-12 no-padding">
    <div class="content-box-header">
      <div class="panel-title">Content</div>
    </div><!--content-box-header-->
    <div class="admin-content-box content-box-large box-with-header">
      <div class="row">

        <div class="col-md-4">
          <h3> Pages </h3>
          <p class="tip"> Manage pages content and text. </p>
          <ul>
            <li> <%= link_to 'Home page', edit_home_field_path(1) %> </li>
            <% @pages.each do |page| %>
              <li> <%= link_to page.page_title, edit_content_management_page_path(page) %> </li>
            <% end %>
            <li> <%= link_to 'FAQs Page', admin_faqs_path %> </li>
            <li> <%= link_to 'Further Readings', admin_further_reads_path %> </li>
          </ul>
        </div>

        <div class="col-md-4">
          <h3> People </h3>
          <p class="tip"> Team members, advisors, and authors. </p>
          <ul>
          <% @people.each do |p| %>
            <li> <%= link_to p.name, person_path(p) %> </li>
          <% end %>
          </ul>
          <div class="admin-links">
            <i class="fa fa-pencil-square-o"></i>
            <%= link_to 'Manage People', admin_people_path %>
          </div>
        </div>

        <div class="col-md-4">
          <h3> Quotes </h3>
          <p class="tip"> Manage quote to appear on news/analysis page. </p>
          <ul>
          <% @quotes.each do |quote| %>
            <li> <%= link_to quote.quote[0..100], quote_path(quote) %> </li>
          <% end %>
          </ul>
          <div class="admin-links">
            <i class="fa fa-pencil-square-o"></i>
            <%= link_to 'Manage Quotes', admin_quotes_path %>
          </div>
        </div>

      </div><!--row-->

    </div><!--content-box-large-->
  </div><!--col-md-12-->

<% else %>
  <%=render "home/permissions_notifications" %>
<% end %>

app/views/home/error.html.erb
<div class="container submit-page">

	<div class="white-box">
		<h2> <%= t(:error_page) %> </h2>
		<p> <%= t(:error_page_message) %> </p>
		<br/>
	</div>

</div>

app/views/home/index.html.erb
<%
meta og: {
  image: "#{root_url}oc.jpg",
  title: "onlinecensorship.org",
  description: t(:website_description)
}
%>

<%= render 'header' %>

<section class="appeal">
  <div class="container">
    <div class="row flex">
      <div class="col-sm-8">
        <h1> <%=@home_fields.appeal_text%> </h1>
      </div>
      <div class="col-sm-4">
        <%= link_to @home_fields.appeal_btn_text, resources_how_to_appeal_path, :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</section>

<%= render 'carousel' %>

<section class="about-oc">
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h1> <%=@home_fields.what_oc_title%> </h1>
      <%= image_tag("magnify-sm", size: "200x200", class: 'hidden-sm hidden-xs center-block') %>
    </div>
    <div class="col-md-6 col-md-offset-2">
      <p> <%=@home_fields.what_oc_text%> </p>
      <p>
        <%= link_to @home_fields.submit_btn_text, new_takedown_path, class: 'btn btn-primary' %>
      </p>
    </div>
  </div>
</div>
</section>

<%= render 'news' %>

app/views/home/maintenance.html.erb
<div class="container submit-page">

	<div class="white-box">
		<h2> We’re offline for a few days to transition to a new, simpler survey format. The new survey will be available by November 28. In the meantime, you can <%= link_to "contact us", contacts_path %> with questions. Thank you for your patience! </h2>
		<br/>
	</div>

</div>